name: Apidog Automation

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar Apidog CLI
        run: npm install -g apidog-cli

      - name: Ejecutar pruebas Apidog
        run: apidog run --project-id TU_PROJECT_ID --token TU_TOKEN
